### ISSUE TITLE
[nocfw branch] Can't load a payload from CTRNAND; it just shuts down

### ISSUE THREAD

**Issue by thedax** [AuroraWright/arm9loaderhax#12]
I figured I'd give this branch a try and load a payload from NAND, but it just shuts down the console. As far as I can tell, it requires the payload to be named arm9loaderhax.bin, located at the root of the CTRNAND partition, is this correct? If so, something seems to be not happening correctly. I double checked for typos, but it just shuts down no matter what I do.

I'm on a New 3DS XL running 11.1.0 on sysNAND, with https://github.com/AuroraWright/arm9loaderhax/commit/b228c9ff6bb7ab0fc03cedb57e76fd7d6a50e05f as the commit being used.

**Comment by AuroraWright** [comment]
It works fine on my New 3DS XL :/ With arm9loaderhax.bin on CTRNAND root.

**Comment by AuroraWright** [comment]
Ah, turns out it only worked if the SD was not mounted beforehand (FatFs quirks lol), which was the only way I tested (for Luma). Now it also works when no SD payload is found. https://github.com/AuroraWright/arm9loaderhax/commit/12f7c20e3375dea8adf13b62b53a6a1e3a537b0d

**Comment by thedax** [comment]
Thanks, will give it a try.

**Comment by thedax** [comment]
It's working fine, but I have one more question: is it possible to also try and boot the NAND payload if the SD card isn't in at all, or is that a limitation of fatfs/the sdmmc "library"? In that scenario, it also just shuts down.

**Comment by AuroraWright** [comment]
If the SD isn't inserted, it was working fine beforehand. I've been making Luma work from CTRNAND with this. Plus, people have installed it and are using it with no SD right now

**Comment by thedax** [comment]
I'll give Luma a quick try to see if it's my payload.

**Comment by thedax** [comment]
It's something on my end in my payload, time to debug. :p
Thanks again.
