### ISSUE TITLE
screen init just for Gateway

### ISSUE THREAD

**Issue by shadowofdarkness** [AuroraWright/arm9loaderhax#3]
I prefer to use your no screen init version for normal usage but Gateway's payload only works with the screen init version. Is it possible to just init the screen for the one GW payload but nothing else?

I only use my Gateway about 1 in 200 boots and hate the idea of staying on the screen init version full time just for the rare times it is actually needed.

Even if you don't have a Gateway just having the arm9loaderhax.bin and Launcher.dat should be enough to test if you can get to the Gateway menu.

**Comment by Margen67** [comment]
Don't worry. They'll add a noscreeninit payload _Soon_™

**Comment by mariogamer2** [comment]
Probably no,not just for gateway.

**Comment by ghost** [comment]
Support the original, not the imitator. 
That's why we should close this issue, unfixed.

**Comment by mariogamer2** [comment]
@idgrepthat  exactly...

**Comment by fox8091** [comment]
This should be fixed. Just use a non screen init payload with a custom BootCtr9 or something. :P

**Comment by GerbilSoft** [comment]
Starting with commit c8e3af3, screen init is determined by the payload filename (arm9loaderhax.bin for no-screen-init, arm9loaderhax_si.bin for screen-init). This issue can probably be closed. (or closed when a release is made?)
