### ISSUE TITLE
GW payload not working since arm9lh v2 

### ISSUE THREAD

**Issue by ArKaWu** [AuroraWright/arm9loaderhax#4]
I know they probably used an outdated setup to quickly provide it after the negative feedback, but since there was nowhere written on the guide that v2 breaks compatability with some payloads but rather adds support for larger ones, I blindly updated.
I could downgrade my sysNAND, remove a9lh, install v1 and update my sysNAND again but that is rather cumbersome.
If there is a way to fix it that would be great.
If not, then I guess I'll do the things mentioned above.

**Comment by mariogamer2** [comment]
Gateway is really not the priority,particularly now...

**Comment by ArKaWu** [comment]
Well I already did the steps above so it's alright.
Deleting all traces of the v1 installer from the guide is not the best way to do things, even if maintaining compatability with old payloads isn't of enough priority.
If this issue is not that important I will close it of course, looking at old github revisions to find the old downloads is not that user friendly but it works for now, so if anyone wants to the same steps as me go ahead.
