### ISSUE TITLE
non screen int arm9loaderhax not booting

### ISSUE THREAD

**Issue by redgraved** [AuroraWright/arm9loaderhax#6]
my arm9loaderhax install with no screeninit fork is not booting any payload(n3ds)
stuck in black screen and blue led if sd card is inserted
else it shutsdown.
pl help

**Comment by Autz64** [comment]
The update went wrong, or you didn't update correctly. Also, check if you have an arm9loaderhax.bin on the root of your SD, or use another SD with the same files.

If none of that works, then your N3DS is bricked, so try to inject a NAND backup without the A9LH installed and redo the A9LH tutorial.
