### ISSUE TITLE
A9LH doesn't clear screen before turning on backlight

### ISSUE THREAD

**Issue by gnmmarechal** [AuroraWright/arm9loaderhax#7]
As per:

https://gbatemp.net/threads/corbenik-another-cfw-for-advanced-users-with-bytecode-patches.429612/page-69#post-6555234

It results in some screen garbage when turning on, if using /arm9loaderhax_si.bin

**Comment by Robomandude** [comment]
This can be used for an ultra light splash screen that doesn't delay boot!
I can see this as an accidental feature.

**Comment by gnmmarechal** [comment]
It causes screen garbage. I see this as useless.

**Comment by Robomandude** [comment]
It just displays what's in the screenbuffer.
It can be filled with a splash screen or blanked out.

**Comment by gnmmarechal** [comment]
As long as the garbage disappears, I'm ok with whatever.

**Comment by AuroraWright** [comment]
It does clear the FBs.
