### ISSUE TITLE
Part 3 Section 1-2

### ISSUE THREAD

**Issue by Gunblade08** [AuroraWright/arm9loaderhax#9]
so this is what i have in my sd card but somehow the dukesrg site still does not load up. cleared saved data, takes me to a google search of the problem im having. ![image](https://cloud.githubusercontent.com/assets/21990804/18282344/9b3f180a-7415-11e6-8055-b8c36727d056.png)

**Comment by Gunblade08** [comment]
ok so i found out im not supposed to google the link, to type it in the url section. in doing so i get the glitched touch screen but doesnt boot down when i press select. i turned it of after the 10 or so seconds and when i take off the sd card to look for the OTP.bin its still not in the folder it is suppose to be in.

**Comment by michaelcassius** [comment]
Having exact same issue  - been painfully following every detail, can't see what's going wrong... Started in 9.20, now stuck on 2.4...
